services:
  - type: web
    name: crewai-research-system
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: /app/src
      - key: FLASK_ENV
        value: production