research_task:
  description: >
    Conduct a thorough research about {topic} using web search tools to find the most current information.
    Use the Web Search tool to find recent developments, trends, and news about {topic}.
    Use the News Search tool to find the latest news and announcements related to {topic}.
    Make sure you find any interesting and relevant information given the current year is {current_year}.
    Focus on recent developments, breakthroughs, and current trends.
  expected_output: >
    A list with 10 bullet points of the most relevant and current information about {topic}, 
    including recent developments, news, and trends from {current_year}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
